### ISSUE TITLE
[Suggestion] Global setting for all boss mobs

### ISSUE THREAD

**Issue by TheDeviantCrafter** [whizzball1/ApatheticMobs#1]
Forge has an `isBoss` flag that most mods add to their boss mobs. I believe the vanilla bosses have this by default. Botania uses this for the Bellethorn if you'd like an open-source example.

I'd like to be able to set all boss mobs to hostile. This should take priority over other settings.

I don't like being randomly attacked while building, but bosses should probably try to kill me.

**Comment by whizzball1** [comment]
This makes sense, especially for boss mobs that don't need custom implementations. I'll make this as soon as possible.

**Comment by whizzball1** [comment]
Closed with version 1.4.1.
