### ISSUE TITLE
Crash on load in combination with Mystic World

### ISSUE THREAD

**Issue by jolandepoel** [whizzball1/ApatheticMobs#6]
Can I just say: thank you so much for making this! I tried peaceful scripts, but if it doesn't come with the pack (like in Undiscovered) it's a real hassle. This is an excellent alternative.

I'm playing Enigmatica 2, but always update everything to the latest version that works, including my forge version. 

Unfortunately, now it crashes. I installed it without editing any of the config, and it worked.
But now I've changed the config to mobs taking revenge and I get a Mystic World crash, but scanning the log, Apathetic Mobs seems to be the culprit instead. 
Disabling only Apathetic Mobs fixes it, disabling Mystic World (which automatically disabled Roots) fixes it, and disabling Revenge Mode fixes it. Enabling Revenge Mode but disabling the revenge timer still crashes it. 

Crash report: https://pastebin.com/exf1MX59

I will post this to the Mystic World issue tracker as well, in case that's helpful.

**Comment by duely** [comment]
This is most likely (I haven't looked at the code yet) a result of the instantiation of entities with a null world for Just Enough Resources integration triggering the capability attachment. You probably just want to bail if entity.(get?)world is null.

**Comment by whizzball1** [comment]
Thanks for letting me know, both of you! Based on @duely's comment I think I can fix this. I'll let you know when I've pushed the new version.

**Comment by whizzball1** [comment]
https://github.com/whizzball1/ApatheticMobs/releases/tag/1.4.1-hotfix

Please test this release!

**Comment by jolandepoel** [comment]
That fixed it perfectly.
