### ISSUE TITLE
Crash when attacking Zombies

### ISSUE THREAD

**Issue by ThaWade** [whizzball1/ApatheticMobs#8]
Game crashes when attacking a zombie.
Zombies - [crash_ZOMBIE.txt](https://github.com/whizzball1/ApatheticMobs/files/3747281/crash_ZOMBIE.txt)
Tamed Wolf - [crash_WOLF.txt](https://github.com/whizzball1/ApatheticMobs/files/3747282/crash_WOLF.txt)
Skeletons - OK
Spiders - OK
Witches - OK
Husk - OK
No other mobs tested.

**Comment by whizzball1** [comment]
Hi! I’m fixing this as soon as the next update comes out. It should be pushed today.

Thanks for letting me know!

God bless you.

**Comment by ThaWade** [comment]
Great! Love the mod thanks!
